/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

/**
 *
 * @author SENA
 */
public class IFclientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form fclientes
     */
    public IFclientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        a15 = new javax.swing.JLabel();
        volver_Vendedor = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLNombre3 = new javax.swing.JLabel();
        jLid3 = new javax.swing.JLabel();
        jLApellido3 = new javax.swing.JLabel();
        JTClient_ID = new javax.swing.JTextField();
        JTClient_Nombre = new javax.swing.JTextField();
        JTClient_Apellido = new javax.swing.JTextField();
        JBClient_Guardar = new javax.swing.JButton();
        JBClient_Mostrar = new javax.swing.JButton();
        JBClient_Buscar = new javax.swing.JButton();
        jLApellido4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Client = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel16.setBackground(new java.awt.Color(0, 102, 255));

        a15.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        a15.setForeground(new java.awt.Color(255, 255, 255));
        a15.setText("Formulario de clientes");

        volver_Vendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volver_Vendedor.setText("<<");
        volver_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_VendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jLNombre3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLNombre3.setText("Nombre");

        jLid3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLid3.setText("Id");

        jLApellido3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLApellido3.setText("Apellido");

        JTClient_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTClient_IDActionPerformed(evt);
            }
        });

        JTClient_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTClient_NombreActionPerformed(evt);
            }
        });

        JTClient_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTClient_ApellidoActionPerformed(evt);
            }
        });

        JBClient_Guardar.setText("Guardar");

        JBClient_Mostrar.setText("Mostrar");

        JBClient_Buscar.setText("Buscar");
        JBClient_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBClient_BuscarActionPerformed(evt);
            }
        });

        jLApellido4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(JBClient_Guardar)
                        .addGap(29, 29, 29)
                        .addComponent(JBClient_Mostrar)
                        .addGap(30, 30, 30)
                        .addComponent(JBClient_Buscar))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLApellido3)
                            .addComponent(jLNombre3)
                            .addComponent(jLid3)
                            .addComponent(jLApellido4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTClient_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(JTClient_Nombre)
                            .addComponent(JTClient_Apellido))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTClient_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLid3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTClient_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido3)
                    .addComponent(JTClient_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLApellido4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBClient_Guardar)
                    .addComponent(JBClient_Mostrar)
                    .addComponent(JBClient_Buscar))
                .addGap(26, 26, 26))
        );

        JTable_Client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_Client);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTClient_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTClient_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTClient_IDActionPerformed

    private void JTClient_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTClient_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTClient_NombreActionPerformed

    private void JTClient_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTClient_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTClient_ApellidoActionPerformed

    private void JBClient_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBClient_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBClient_BuscarActionPerformed

    private void volver_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_VendedorActionPerformed
    
    }//GEN-LAST:event_volver_VendedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBClient_Buscar;
    public javax.swing.JButton JBClient_Guardar;
    public javax.swing.JButton JBClient_Mostrar;
    public javax.swing.JTextField JTClient_Apellido;
    public javax.swing.JTextField JTClient_ID;
    public javax.swing.JTextField JTClient_Nombre;
    public javax.swing.JTable JTable_Client;
    private javax.swing.JLabel a15;
    private javax.swing.JLabel jLApellido3;
    private javax.swing.JLabel jLApellido4;
    private javax.swing.JLabel jLNombre3;
    private javax.swing.JLabel jLid3;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton volver_Vendedor;
    // End of variables declaration//GEN-END:variables
}
